export const FAMILY_DATA = {
  groomFamily: {
    title: "Nhà Trai",
    name: "Trần Văn Việt",
    fatherName: "Trần Văn Dũng",
    motherName: "Nguyễn Thị Oanh",
    address1: `Hồi Cương - Ngũ Kiên\nVĩnh Tường - Vĩnh Phúc`,
    address2: `Hồi Cương - Ngũ Kiên - Vĩnh Tường - Vĩnh Phúc`,
    time: "16 GIỜ 30",
    dayOfWeek: "CHỦ NHẬT",
    date: "01",
    month: "12",
    year: "2024",
    lunar: "( Nhằm ngày 01 tháng 11 năm Giáp Thìn )",
  },
  brideFamily: {
    title: "Nhà Gái",
    name: "Đỗ Thị Huyền Trang",
    fatherName: "Đỗ Trung Tưởng",
    motherName: "Trần Thị Tuất",
    address1: `Duy Bình - Vĩnh Ninh\nVĩnh Tường - Vĩnh Phúc`,
    address2: `Duy Bình - Vĩnh Ninh - Vĩnh Tường - Vĩnh Phúc`,
    time: "16 GIỜ 30",
    dayOfWeek: "CHỦ NHẬT",
    date: "01",
    month: "12",
    year: "2024",
    lunar: "( Nhằm ngày 01 tháng 11 năm Giáp Thìn )",
  },
};
